# Generated by Django 2.1.7 on 2019-04-21 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blo', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
